In [76]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [77]:
df = pd.read_csv('kc_house_data.csv')


In [78]:
df

id        date     price  bedrooms  bathrooms  sqft_living  \
0      7129300520  10/13/2014  221900.0         3       1.00         1180   
1      6414100192   12/9/2014  538000.0         3       2.25         2570   
2      5631500400   2/25/2015  180000.0         2       1.00          770   
3      2487200875   12/9/2014  604000.0         4       3.00         1960   
4      1954400510   2/18/2015  510000.0         3       2.00         1680   
...           ...         ...       ...       ...        ...          ...   
21592   263000018   5/21/2014  360000.0         3       2.50         1530   
21593  6600060120   2/23/2015  400000.0         4       2.50         2310   
21594  1523300141   6/23/2014  402101.0         2       0.75         1020   
21595   291310100   1/16/2015  400000.0         3       2.50         1600   
21596  1523300157  10/15/2014  325000.0         2       0.75         1020   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
0          5650     1.0         NaN   0.0  ...      7        1180   
1          7242     2.0         0.0   0.0  ...      7        2170   
2         10000     1.0         0.0   0.0  ...      6         770   
3          5000     1.0         0.0   0.0  ...      7        1050   
4          8080     1.0         0.0   0.0  ...      8        1680   
...         ...     ...         ...   ...  ...    ...         ...   
21592      1131     3.0         0.0   0.0  ...      8        1530   
21593      5813     2.0         0.0   0.0  ...      8        2310   
21594      1350     2.0         0.0   0.0  ...      7        1020   
21595      2388     2.0         NaN   0.0  ...      8        1600   
21596      1076     2.0         0.0   0.0  ...      7        1020   

       sqft_basement yr_built  yr_renovated  zipcode      lat     long  \
0                0.0     1955           0.0    98178  47.5112 -122.257   
1              400.0     1951        1991.0    98125  47.7210 -122.319   
2                0.0     1933           NaN    98028  47.7379 -122.233   
3              910.0     1965           0.0    98136  47.5208 -122.393   
4                0.0     1987           0.0    98074  47.6168 -122.045   
...              ...      ...           ...      ...      ...      ...   
21592            0.0     2009           0.0    98103  47.6993 -122.346   
21593            0.0     2014           0.0    98146  47.5107 -122.362   
21594            0.0     2009           0.0    98144  47.5944 -122.299   
21595            0.0     2004           0.0    98027  47.5345 -122.069   
21596            0.0     2008           0.0    98144  47.5941 -122.299   

       sqft_living15  sqft_lot15  
0               1340        5650  
1               1690        7639  
2               2720        8062  
3               1360        5000  
4               1800        7503  
...              ...         ...  
21592           1530        1509  
21593           1830        7200  
21594           1020        2007  
21595           1410        1287  
21596           1020        1357  

[21597 rows x 21 columns]

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 21 columns):
id               21597 non-null int64
date             21597 non-null object
price            21597 non-null float64
bedrooms         21597 non-null int64
bathrooms        21597 non-null float64
sqft_living      21597 non-null int64
sqft_lot         21597 non-null int64
floors           21597 non-null float64
waterfront       19221 non-null float64
view             21534 non-null float64
condition        21597 non-null int64
grade            21597 non-null int64
sqft_above       21597 non-null int64
sqft_basement    21597 non-null object
yr_built         21597 non-null int64
yr_renovated     17755 non-null float64
zipcode          21597 non-null int64
lat              21597 non-null float64
long             21597 non-null float64
sqft_living15    21597 non-null int64
sqft_lot15       21597 non-null int64
dtypes: float64(8), int64(11), object(2)
memory usage: 3.5+ MB


In [80]:
# checking total missing values
df.isna().sum()

id                  0
date                0
price               0
bedrooms            0
bathrooms           0
sqft_living         0
sqft_lot            0
floors              0
waterfront       2376
view               63
condition           0
grade               0
sqft_above          0
sqft_basement       0
yr_built            0
yr_renovated     3842
zipcode             0
lat                 0
long                0
sqft_living15       0
sqft_lot15          0
dtype: int64

In [81]:
df['waterfront'].unique()

array([nan,  0.,  1.])

In [82]:
# turning nans to 0 and creating a new column
waterfront_boolean = []
for i in range(0,len(df['waterfront'])):
    if df['waterfront'][i] == 0.0:
        waterfront_boolean.append(0.0)
    elif df['waterfront'].isna()[i] == True:
        waterfront_boolean.append(0.0)
    else:
        waterfront_boolean.append(1.0)
df['waterfront_bool'] = waterfront_boolean

In [83]:
df['view'].value_counts()

0.0    19422
2.0      957
3.0      508
1.0      330
4.0      317
Name: view, dtype: int64

In [84]:
df['view'].unique()

array([ 0., nan,  3.,  4.,  2.,  1.])

In [85]:
# same process of waterfronts
view_boolean = []
for i in range(0,len(df['view'])):
    if df['view'].isna()[i] == True:
        view_boolean.append(0.0)
    else:
        view_boolean.append(df['view'][i])
df['view_cleaned'] = view_boolean

In [86]:
df['view_cleaned'].unique()

array([0., 3., 4., 2., 1.])

In [87]:
df['yr_renovated'].value_counts()

0.0       17011
2014.0       73
2003.0       31
2013.0       31
2007.0       30
          ...  
1946.0        1
1959.0        1
1971.0        1
1951.0        1
1954.0        1
Name: yr_renovated, Length: 70, dtype: int64

In [88]:
df['yr_renovated'].unique()

array([   0., 1991.,   nan, 2002., 2010., 1992., 2013., 1994., 1978.,
       2005., 2003., 1984., 1954., 2014., 2011., 1983., 1945., 1990.,
       1988., 1977., 1981., 1995., 2000., 1999., 1998., 1970., 1989.,
       2004., 1986., 2007., 1987., 2006., 1985., 2001., 1980., 1971.,
       1979., 1997., 1950., 1969., 1948., 2009., 2015., 1974., 2008.,
       1968., 2012., 1963., 1951., 1962., 1953., 1993., 1996., 1955.,
       1982., 1956., 1940., 1976., 1946., 1975., 1964., 1973., 1957.,
       1959., 1960., 1967., 1965., 1934., 1972., 1944., 1958.])

In [89]:
# same here, this time turning nans to 0 and the rest to 1, where:
# 0 = not renovated
# 1 = renovated
renovated_boolean = []
for i in range(0,len(df['yr_renovated'])):
    if df['yr_renovated'][i] == 0.0:
        renovated_boolean.append(0.0)
    elif df['yr_renovated'].isna()[i] == True:
        renovated_boolean.append(0.0)
    else:
        renovated_boolean.append(1.0)
df['renovated_bool'] = renovated_boolean

In [90]:
renovated_boolean

[0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0

In [91]:
# splitting sale date in two separate year and month columns
year_sold = []
month_sold = []
for i in range(0,len(df['date'])):
    split_date = df['date'][i].split('/')
    
    year_sold.append(int(split_date[2]) - df['yr_built'][i])
    month_sold.append(int(split_date[0]))
    
df['age_when_sold'] = year_sold
df['month_of_sale'] = month_sold

In [92]:
df['month_of_sale'].unique()   

array([10, 12,  2,  5,  6,  1,  4,  3,  7,  8, 11,  9])

In [93]:
df['age_when_sold'].unique()

array([ 59,  63,  82,  49,  28,  13,  19,  52,  55,  12,  50,  72,  87,
        37, 115,  36,  20,  98,  93,  46,  67,  29,  73,  99, 105,  66,
        10,  11,   9,  85,  33,  84,  81, 110,  18,  14,  30,   0,  92,
        62,  64,  34,  88,   6,  24,  60,  41,  35,  89,  25,  43,  58,
        74,  22,  51,  53,   8,  26,  75,  68,  48,  39, 104,  31, 114,
         4,  69,  65,  90,  27, 101,  47,  54, 109,   7,  61,  15,  38,
        16, 113,  21,  94,  45, 100, 111,  96,  97,  86, 103,  78,  77,
        76, 107,  40,  57, 102,  17,  71,   1,  23,  91,  42,  95,   2,
        32,   3,  56,  70,  44, 112,   5,  80,  83, 106, 108,  79,  -1])

In [94]:
# assuming -1 means the house has been sold before building completion finished, turning it to 0
age_cleaned = []
for i in range(0,len(df['age_when_sold'])):
    if df['age_when_sold'][i] == -1:
        age_cleaned.append(0.0)
    else:
        age_cleaned.append(df['age_when_sold'][i])
df['age_when_sold'] = age_cleaned

In [95]:
df['age_when_sold'].unique()

array([ 59.,  63.,  82.,  49.,  28.,  13.,  19.,  52.,  55.,  12.,  50.,
        72.,  87.,  37., 115.,  36.,  20.,  98.,  93.,  46.,  67.,  29.,
        73.,  99., 105.,  66.,  10.,  11.,   9.,  85.,  33.,  84.,  81.,
       110.,  18.,  14.,  30.,   0.,  92.,  62.,  64.,  34.,  88.,   6.,
        24.,  60.,  41.,  35.,  89.,  25.,  43.,  58.,  74.,  22.,  51.,
        53.,   8.,  26.,  75.,  68.,  48.,  39., 104.,  31., 114.,   4.,
        69.,  65.,  90.,  27., 101.,  47.,  54., 109.,   7.,  61.,  15.,
        38.,  16., 113.,  21.,  94.,  45., 100., 111.,  96.,  97.,  86.,
       103.,  78.,  77.,  76., 107.,  40.,  57., 102.,  17.,  71.,   1.,
        23.,  91.,  42.,  95.,   2.,  32.,   3.,  56.,  70.,  44., 112.,
         5.,  80.,  83., 106., 108.,  79.])

In [96]:
# checking for outliers
for col in df.columns:
    print(df[col].value_counts(), '\n\n')

795000620     3
1825069031    2
2019200220    2
7129304540    2
1781500435    2
             ..
7812801125    1
4364700875    1
3021059276    1
880000205     1
1777500160    1
Name: id, Length: 21420, dtype: int64 


6/23/2014     142
6/26/2014     131
6/25/2014     131
7/8/2014      127
4/27/2015     126
             ... 
5/15/2015       1
8/30/2014       1
11/30/2014      1
2/15/2015       1
8/3/2014        1
Name: date, Length: 372, dtype: int64 


350000.0    172
450000.0    172
550000.0    159
500000.0    152
425000.0    150
           ... 
870515.0      1
336950.0      1
386100.0      1
176250.0      1
884744.0      1
Name: price, Length: 3622, dtype: int64 


3     9824
4     6882
2     2760
5     1601
6      272
1      196
7       38
8       13
9        6
10       3
11       1
33       1
Name: bedrooms, dtype: int64 


2.50    5377
1.00    3851
1.75    3048
2.25    2047
2.00    1930
1.50    1445
2.75    1185
3.00     753
3.50     731
3.25     589
3.75     155
4.00     136
4.50 

In [97]:
df['sqft_basement'].loc[df['sqft_basement'] == '?']

6        ?
18       ?
42       ?
79       ?
112      ?
        ..
21442    ?
21447    ?
21473    ?
21519    ?
21581    ?
Name: sqft_basement, Length: 454, dtype: object

In [98]:
# changing ? to 0
basement_filler = []
for i in range(0,len(df)):
    if df['sqft_basement'][i] == '?':
        basement_filler.append('0.0')
    else:
        basement_filler.append(df['sqft_basement'][i])
df['sqft_basement'] = basement_filler

df['sqft_basement'] = df['sqft_basement'].astype(float)

In [99]:
df['sqft_basement'].value_counts()

0.0       13280
600.0       217
500.0       209
700.0       208
800.0       201
          ...  
915.0         1
295.0         1
1281.0        1
2130.0        1
906.0         1
Name: sqft_basement, Length: 303, dtype: int64

In [100]:
df.loc[df['bedrooms'] == 33]

id       date     price  bedrooms  bathrooms  sqft_living  \
15856  2402100895  6/25/2014  640000.0        33       1.75         1620   

       sqft_lot  floors  waterfront  view  ...  zipcode      lat     long  \
15856      6000     1.0         0.0   0.0  ...    98103  47.6878 -122.331   

       sqft_living15  sqft_lot15  waterfront_bool  view_cleaned  \
15856           1330        4700              0.0           0.0   

       renovated_bool  age_when_sold  month_of_sale  
15856             0.0           67.0              6  

[1 rows x 26 columns]

In [101]:
df.loc[df['sqft_lot'] == 315374]

id       date     price  bedrooms  bathrooms  sqft_living  \
145  1526069017  12/3/2014  921500.0         4        2.5         3670   

     sqft_lot  floors  waterfront  view  ...  zipcode      lat     long  \
145    315374     2.0         0.0   0.0  ...    98077  47.7421 -122.026   

     sqft_living15  sqft_lot15  waterfront_bool  view_cleaned  renovated_bool  \
145           2840       87991              0.0           0.0             0.0   

     age_when_sold  month_of_sale  
145           20.0             12  

[1 rows x 26 columns]

In [102]:
df.loc[df['sqft_living'] > 12500]

id      date      price  bedrooms  bathrooms  sqft_living  \
12764  1225069038  5/5/2014  2280000.0         7        8.0        13540   

       sqft_lot  floors  waterfront  view  ...  zipcode      lat     long  \
12764    307752     3.0         0.0   4.0  ...    98053  47.6675 -121.986   

       sqft_living15  sqft_lot15  waterfront_bool  view_cleaned  \
12764           4850      217800              0.0           4.0   

       renovated_bool  age_when_sold  month_of_sale  
12764             0.0           15.0              5  

[1 rows x 26 columns]

In [103]:
# dropping outliers
df = df.drop(15856)
df = df.drop(145)
df = df.drop(12764)

In [104]:
df = df.drop_duplicates(subset = 'id')

In [105]:
# resetting index and creating a new clean dataframe
df.reset_index(inplace = True, drop=False)
df.drop(['index'], axis=1, inplace=True)
df

id        date     price  bedrooms  bathrooms  sqft_living  \
0      7129300520  10/13/2014  221900.0         3       1.00         1180   
1      6414100192   12/9/2014  538000.0         3       2.25         2570   
2      5631500400   2/25/2015  180000.0         2       1.00          770   
3      2487200875   12/9/2014  604000.0         4       3.00         1960   
4      1954400510   2/18/2015  510000.0         3       2.00         1680   
...           ...         ...       ...       ...        ...          ...   
21412   263000018   5/21/2014  360000.0         3       2.50         1530   
21413  6600060120   2/23/2015  400000.0         4       2.50         2310   
21414  1523300141   6/23/2014  402101.0         2       0.75         1020   
21415   291310100   1/16/2015  400000.0         3       2.50         1600   
21416  1523300157  10/15/2014  325000.0         2       0.75         1020   

       sqft_lot  floors  waterfront  view  ...  zipcode      lat     long  \
0          5650     1.0         NaN   0.0  ...    98178  47.5112 -122.257   
1          7242     2.0         0.0   0.0  ...    98125  47.7210 -122.319   
2         10000     1.0         0.0   0.0  ...    98028  47.7379 -122.233   
3          5000     1.0         0.0   0.0  ...    98136  47.5208 -122.393   
4          8080     1.0         0.0   0.0  ...    98074  47.6168 -122.045   
...         ...     ...         ...   ...  ...      ...      ...      ...   
21412      1131     3.0         0.0   0.0  ...    98103  47.6993 -122.346   
21413      5813     2.0         0.0   0.0  ...    98146  47.5107 -122.362   
21414      1350     2.0         0.0   0.0  ...    98144  47.5944 -122.299   
21415      2388     2.0         NaN   0.0  ...    98027  47.5345 -122.069   
21416      1076     2.0         0.0   0.0  ...    98144  47.5941 -122.299   

       sqft_living15  sqft_lot15  waterfront_bool  view_cleaned  \
0               1340        5650              0.0           0.0   
1               1690        7639              0.0           0.0   
2               2720        8062              0.0           0.0   
3               1360        5000              0.0           0.0   
4               1800        7503              0.0           0.0   
...              ...         ...              ...           ...   
21412           1530        1509              0.0           0.0   
21413           1830        7200              0.0           0.0   
21414           1020        2007              0.0           0.0   
21415           1410        1287              0.0           0.0   
21416           1020        1357              0.0           0.0   

       renovated_bool  age_when_sold  month_of_sale  
0                 0.0           59.0             10  
1                 1.0           63.0             12  
2                 0.0           82.0              2  
3                 0.0           49.0             12  
4                 0.0           28.0              2  
...               ...            ...            ...  
21412             0.0            5.0              5  
21413             0.0            1.0              2  
21414             0.0            5.0              6  
21415             0.0           11.0              1  
21416             0.0            6.0             10  

[21417 rows x 26 columns]

In [106]:
df_clean = df

In [107]:
df_clean

id        date     price  bedrooms  bathrooms  sqft_living  \
0      7129300520  10/13/2014  221900.0         3       1.00         1180   
1      6414100192   12/9/2014  538000.0         3       2.25         2570   
2      5631500400   2/25/2015  180000.0         2       1.00          770   
3      2487200875   12/9/2014  604000.0         4       3.00         1960   
4      1954400510   2/18/2015  510000.0         3       2.00         1680   
...           ...         ...       ...       ...        ...          ...   
21412   263000018   5/21/2014  360000.0         3       2.50         1530   
21413  6600060120   2/23/2015  400000.0         4       2.50         2310   
21414  1523300141   6/23/2014  402101.0         2       0.75         1020   
21415   291310100   1/16/2015  400000.0         3       2.50         1600   
21416  1523300157  10/15/2014  325000.0         2       0.75         1020   

       sqft_lot  floors  waterfront  view  ...  zipcode      lat     long  \
0          5650     1.0         NaN   0.0  ...    98178  47.5112 -122.257   
1          7242     2.0         0.0   0.0  ...    98125  47.7210 -122.319   
2         10000     1.0         0.0   0.0  ...    98028  47.7379 -122.233   
3          5000     1.0         0.0   0.0  ...    98136  47.5208 -122.393   
4          8080     1.0         0.0   0.0  ...    98074  47.6168 -122.045   
...         ...     ...         ...   ...  ...      ...      ...      ...   
21412      1131     3.0         0.0   0.0  ...    98103  47.6993 -122.346   
21413      5813     2.0         0.0   0.0  ...    98146  47.5107 -122.362   
21414      1350     2.0         0.0   0.0  ...    98144  47.5944 -122.299   
21415      2388     2.0         NaN   0.0  ...    98027  47.5345 -122.069   
21416      1076     2.0         0.0   0.0  ...    98144  47.5941 -122.299   

       sqft_living15  sqft_lot15  waterfront_bool  view_cleaned  \
0               1340        5650              0.0           0.0   
1               1690        7639              0.0           0.0   
2               2720        8062              0.0           0.0   
3               1360        5000              0.0           0.0   
4               1800        7503              0.0           0.0   
...              ...         ...              ...           ...   
21412           1530        1509              0.0           0.0   
21413           1830        7200              0.0           0.0   
21414           1020        2007              0.0           0.0   
21415           1410        1287              0.0           0.0   
21416           1020        1357              0.0           0.0   

       renovated_bool  age_when_sold  month_of_sale  
0                 0.0           59.0             10  
1                 1.0           63.0             12  
2                 0.0           82.0              2  
3                 0.0           49.0             12  
4                 0.0           28.0              2  
...               ...            ...            ...  
21412             0.0            5.0              5  
21413             0.0            1.0              2  
21414             0.0            5.0              6  
21415             0.0           11.0              1  
21416             0.0            6.0             10  

[21417 rows x 26 columns]

In [61]:
df_clean.corr()

id     price  bedrooms  bathrooms  sqft_living  \
id               1.000000 -0.018218  0.002123   0.004775    -0.012753   
price           -0.018218  1.000000  0.316096   0.525535     0.702036   
bedrooms         0.002123  0.316096  1.000000   0.528392     0.594255   
bathrooms        0.004775  0.525535  0.528392   1.000000     0.754855   
sqft_living     -0.012753  0.702036  0.594255   0.754855     1.000000   
sqft_lot        -0.132238  0.087466  0.032166   0.085410     0.168924   
floors           0.018310  0.255834  0.183112   0.501568     0.352537   
waterfront      -0.004199  0.277081 -0.002383   0.067443     0.110851   
view             0.011174  0.394731  0.080111   0.183982     0.280008   
condition       -0.024209  0.034868  0.022892  -0.129303    -0.061563   
grade            0.006711  0.667761  0.367283   0.665381     0.763323   
sqft_above      -0.011238  0.604777  0.492986   0.685363     0.876074   
sqft_basement   -0.004540  0.319689  0.302522   0.276038     0.425351   
yr_built         0.021235  0.052701  0.160217   0.506600     0.317205   
yr_renovated    -0.012309  0.130499  0.019084   0.051877     0.055961   
zipcode         -0.007944 -0.052303 -0.159605  -0.203990    -0.199454   
lat             -0.002626  0.305688 -0.013150   0.022890     0.050395   
long             0.019465  0.020586  0.136725   0.223516     0.240062   
sqft_living15   -0.003630  0.584171  0.405746   0.568959     0.756792   
sqft_lot15      -0.139112  0.080818  0.030343   0.085255     0.180180   
waterfront_bool -0.003639  0.265067 -0.002116   0.063752     0.105181   
view_cleaned     0.011358  0.392485  0.079930   0.183550     0.279187   
age_when_sold   -0.021072 -0.052625 -0.160370  -0.506971    -0.317614   
month_of_sale   -0.011496 -0.010507  0.000404   0.005715     0.010553   

                 sqft_lot    floors  waterfront      view  condition  ...  \
id              -0.132238  0.018310   -0.004199  0.011174  -0.024209  ...   
price            0.087466  0.255834    0.277081  0.394731   0.034868  ...   
bedrooms         0.032166  0.183112   -0.002383  0.080111   0.022892  ...   
bathrooms        0.085410  0.501568    0.067443  0.183982  -0.129303  ...   
sqft_living      0.168924  0.352537    0.110851  0.280008  -0.061563  ...   
sqft_lot         1.000000 -0.006820    0.023257  0.074303  -0.009265  ...   
floors          -0.006820  1.000000    0.021667  0.026573  -0.266815  ...   
waterfront       0.023257  0.021667    1.000000  0.407781   0.017584  ...   
view             0.074303  0.026573    0.407781  1.000000   0.045016  ...   
condition       -0.009265 -0.266815    0.017584  0.045016   1.000000  ...   
grade            0.112355  0.457801    0.087535  0.247662  -0.150461  ...   
sqft_above       0.180220  0.522639    0.075650  0.163915  -0.161573  ...   
sqft_basement    0.012262 -0.243727    0.088696  0.269828   0.169354  ...   
yr_built         0.051855  0.488875   -0.026438 -0.056544  -0.365120  ...   
yr_renovated     0.004742  0.002841    0.087393  0.100712  -0.062211  ...   
zipcode         -0.129569 -0.058464    0.031322  0.087723   0.004306  ...   
lat             -0.086724  0.048796   -0.012875  0.005510  -0.015707  ...   
long             0.229849  0.124551   -0.040134 -0.079636  -0.107098  ...   
sqft_living15    0.142408  0.278624    0.089004  0.277519  -0.095136  ...   
sqft_lot15       0.717121 -0.012496    0.032103  0.072089  -0.003317  ...   
waterfront_bool  0.021535  0.020593    1.000000  0.383351   0.016621  ...   
view_cleaned     0.074060  0.026556    0.406229  1.000000   0.044904  ...   
age_when_sold   -0.051756 -0.489156    0.026367  0.056597   0.364407  ...   
month_of_sale   -0.003209  0.012093    0.008068 -0.006472   0.021745  ...   

                 yr_renovated   zipcode       lat      long  sqft_living15  \
id                  -0.012309 -0.007944 -0.002626  0.019465      -0.003630   
price                0.130499 -0.052303  0.305688  0.020586       0.584171   
bedrooms             0.019084 -0.1596