In [152]:
# importing all libraries.
import pandas as pd
import statsmodels.api as sm
import math
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from statsmodels.formula.api import ols
from sklearn import preprocessing
from scipy import stats

%matplotlib inline
plt.style.use('seaborn')

from sklearn.model_selection import train_test_split,KFold,cross_validate
from sklearn.linear_model import LinearRegression

In [153]:
# dropping extra index column.
df_clean_1 = pd.read_csv('df_clean_1.csv')
df_clean_1 = df_clean_1.drop(['Unnamed: 0'], axis=1)

In [154]:
# creating numpy arrays for the latitudes and longitudes of each house that is by the water.
water_lat = np.array(df_clean_1.loc[(df_clean_1['waterfront_bool'] == 1)]['lat'])
water_long = np.array(df_clean_1.loc[(df_clean_1['waterfront_bool'] == 1)]['long'])

# creating numpy arrays for latitudes and longitudes of each house.
house_lat = np.array(df_clean_1['lat'])
house_long = np.array(df_clean_1['long'])
house_id = np.array(df_clean_1['id'])

In [155]:
def find_pairs(water_array, house_array, house_id):
    pairs_found = []
    cross_array = np.absolute(water_array[np.newaxis, :] - house_array[:, np.newaxis])
    for i in range(cross_array.shape[0]):
        row_min = cross_array[i].min()
        col = house_id[np.asscalar((np.where(cross_array[i] == cross_array[i].min())[0]).min())]
        pairs_found.append((row_min, col))
    return pairs_found


In [156]:
df_lat_pairs = pd.DataFrame(find_pairs(water_lat,house_lat,house_id), columns=['y_distance','nearest_house_lat'])
df_long_pairs = pd.DataFrame(find_pairs(water_long,house_long,house_id), columns=['x_distance','nearest_house_long'])
df_pairs = pd.concat([df_lat_pairs,df_long_pairs], axis=1)
df_pairs

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  


y_distance  nearest_house_lat  x_distance  nearest_house_long
0          0.0002         6197800045       0.000          9558200045
1          0.0045         3793500160       0.004          9545240070
2          0.0025         8035350320       0.002          7766200013
3          0.0015         9558200045       0.000          3444100400
4          0.0005         1328310370       0.014          5547700270
...           ...                ...         ...                 ...
21412      0.0004         8820901275       0.002          1321400060
21413      0.0002         1736800520       0.002          2768000400
21414      0.0001         3224079105       0.012          3303700376
21415      0.0003         9478500640       0.001          1328310370
21416      0.0002         3224079105       0.012          3303700376

[21417 rows x 4 columns]

In [176]:
df_pairs['check'] = df_pairs[['y_distance', 'x_distance']].min(axis=1)

In [158]:
cross_array = np.absolute(water_lat[np.newaxis, :] - house_lat[:, np.newaxis])
cross_array[0].min()

0.00019999999999953388

In [159]:
y_dist_to_water

array([0.0002, 0.0045, 0.0025, ..., 0.0001, 0.0003, 0.0002])

In [160]:
# y_dist_to_water = np.amin(np.absolute(house_lat[np.newaxis, :] - water_lat[:, np.newaxis]), axis=0)
# x_dist_to_water = np.amin(np.absolute(house_long[np.newaxis, :] - water_long[:, np.newaxis]), axis=0)

In [161]:
w = np.array([1,2,3,4,5])
h = np.array([2,5,4,6,6,2,1])

In [162]:
y_dist_to_w = np.amin(np.absolute(w[np.newaxis, :] - h[:, np.newaxis]), axis=1)
y_dist_to_w

array([0, 0, 0, 1, 1, 0, 0])

In [163]:
array = np.absolute(w[np.newaxis, :] - h[:, np.newaxis])
array

array([[1, 0, 1, 2, 3],
       [4, 3, 2, 1, 0],
       [3, 2, 1, 0, 1],
       [5, 4, 3, 2, 1],
       [5, 4, 3, 2, 1],
       [1, 0, 1, 2, 3],
       [0, 1, 2, 3, 4]])

In [164]:
def find_pairs(w_array, h_array):
    pairs_found = []
    cross_array = np.absolute(w_array[np.newaxis, :] - h_array[:, np.newaxis])
    for i in range(cross_array.shape[0]):
        row_min = cross_array[i].min()
        col = float(np.where(cross_array[i] == cross_array[i].min())[0])
        col_name = w_array[col]
        pairs_found.append((row_min, col))
    return pairs_found

        
find_pairs(w,h)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
array[:,0]

In [ ]:
array.shape[1]

In [ ]:
df_clean_1[['id','lat']].head()